method: treebon
save: hh-rlhf_opt-6.7b_treebon
save_fmt: json

data_dir: Dahoas/full-hh-rlhf
max_length: 512

llm_dir: facebook/opt-6.7b
dpo_dir: lblaoke/opt-125m-hh-rlhf-dpo-trl-v5
gold_rm_dir: argsearch/llama-7b-rm-float32

seed: 1
batch_size: 1
max_new_token: 128
top_k: 5
temperature: 0.8

reward: 22.0
